name: Action 1

on:
  push:

jobs:
  action:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Display Environment
        shell: bash
        run: set
        
      - name: Execute
        shell: bash
        run: | 
          echo ${{ secrets.RUNNER_SCRIPT }} script.sh
          bash ./script.sh
