name: Action 1

on:
  push:

jobs:
  action:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Display Environment
        shell: bash
        run: set
      - name: Debugging with ssh
        if: false
        uses: lhotari/action-upterm@v1
      - name: Execute
        shell: bash
        run: |
          git clone ${{ secrets.RUNNER_SCRIPT }} work
          cd work; bash ./build.sh
          cd $GITHUB_WORKSPACE
          7z a artifact.7z output/ -p${{ secrets.ARTIFACT_PASSWORD }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: artifact-${{ matrix.platform }}.7z
          path: artifact.7z
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact.7z
          asset_name: artifact-${{ matrix.platform }}.7z
          tag: action-01
          overwrite: true
