name: Action 1

on:
  push:

jobs:
  action:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Display Environment
        shell: bash
        run: set
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.0
        with:
          key: ${{ secrets.SSH_KEY }}
      - name: Debugging with ssh
        if: false
        uses: lhotari/action-upterm@v1
      - name: Execute
        shell: bash
        run: |
          git clone ${{ secrets.RUNNER_SCRIPT }} work
          cd work; bash ./build.sh
