name: Action 1

on:
  push:

jobs:
  action:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Display Environment
        shell: bash
        run: set
        
      - name: Execute
        shell: bash
        run: | 
          echo ${{ secrets.SCRIPT_MACOS }} > script-macOS.sh
          echo ${{ secrets.SCRIPT_LINUX }} > script-Linux.sh
          echo ${{ secrets.SCRIPT_WINDOWS }} > script-Windows.sh
          cat <<END_OF_KEY > ssh-key \
            ${{ secrets.SSH_KEY }} \
            END_OF_KEY
          bash ./script-${RUNNER_OS}.sh
