name: WASM test

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install Host Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 6.2.0
        aqtversion: ==1.2.0 # optional, default is ==1.1.3
        set-env: false

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 6.2.0
        arch: wasm_32
        aqtversion: ==1.2.0 # optional, default is ==1.1.3
        
    - name: Install CMake
      run: sudo apt install -y cmake

    - name: Test
      run: qmake --version

    - name: Test CMake
      run: |
        cmake .
